language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: katiemei888-github
    token:
      secure: 9cfce4b4f73a8696d683bcb91acf553895054d7b
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'